### ISSUE TITLE
huge error on using this library

### ISSUE THREAD

**Issue by hamedrajabpour** [davidsdearaujo/find_dropdown#14]
Hi I Upgraded flutter to new stable version (1.12.13) and i got error when i using this library in my project. error is in following:

`
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/find_dropdown-0.1.7+1/lib/find_dropdown_bloc.dart:9:3: Error: Type 'Observable' not found.
  Observable<String> get validateMessageOut => _validateMessage$;
  ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/find_dropdown-0.1.7+1/lib/find_dropdown_bloc.dart:9:3: Error: Expected 0 type arguments.
  Observable<String> get validateMessageOut => _validateMessage$;
  ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:8:3: Error: Type 'Observable' not found.
  Observable<List<T>> filteredListOut;
  ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:8:3: Error: Expected 0 type arguments.
  Observable<List<T>> filteredListOut;
  ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:9:3: Error: Type 'Observable' not found.
  Observable<List<T>> _filteredListOnlineOut;
  ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:9:3: Error: Expected 0 type arguments.
  Observable<List<T>> _filteredListOnlineOut;
  ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:10:3: Error: Type 'Observable' not found.
  Observable<List<T>> _filteredListOfflineOut;
  ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:10:3: Error: Expected 0 type arguments.
  Observable<List<T>> _filteredListOfflineOut;
  ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:8:3: Error: 'Observable' isn't a type.
  Observable<List<T>> filteredListOut;
  ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:9:3: Error: 'Observable' isn't a type.
  Observable<List<T>> _filteredListOnlineOut;
  ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:10:3: Error: 'Observable' isn't a type.
  Observable<List<T>> _filteredListOfflineOut;
  ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:16:9: Error: The getter 'Observable' isn't defined for the class 'SelectOneBloc<T>'.
 - 'SelectOneBloc' is from 'package:select_dialog/select_bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Observable'.
        Observable.combineLatest2(_list$, _filter$, filter);
        ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:22:29: Error: The getter 'Observable' isn't defined for the class 'SelectOneBloc<T>'.
 - 'SelectOneBloc' is from 'package:select_dialog/select_bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Observable'.
        .switchMap((val) => Observable.fromFuture(onFind(val)).startWith(null));
                            ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:25:9: Error: The getter 'Observable' isn't defined for the class 'SelectOneBloc<T>'.
 - 'SelectOneBloc' is from 'package:select_dialog/select_bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Observable'.
        Observable.merge([_filteredListOfflineOut, _filteredListOnlineOut]);
        ^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`

**Comment by MoacirSchmidt** [comment]
check "Upgrading from RxDart 0.22.x to 0.23.x" from https://pub.dev/packages/rxdart

**Comment by hamedrajabpour** [comment]
i added this library to new flutter project and i got same error and i realy need to this library
if you can fix this issue as soon as posible

**Comment by TheHussein** [comment]
I can confirm this, getting same error, also fresh flutter project.

**Comment by mmmaxi** [comment]
This is very much related to this issue [Issue8](https://github.com/davidsdearaujo/select_dialog/issues/8) and seems to be an RxDart topic.
