### ISSUE TITLE
Flutter web width of the result panel

### ISSUE THREAD

**Issue by danieramiz** [davidsdearaujo/find_dropdown#17]
It is there a way to set custom width to the result panel?
On Web just looks bad taking almost the whole width of the screen.

![image](https://user-images.githubusercontent.com/11200295/76686980-77337a80-65e5-11ea-9317-ca697fe87479.png)

**Comment by danieramiz** [comment]
So this plugin is completely abandoned? and nobody is supporting it?

**Comment by davidsdearaujo** [comment]
Sorry for slowness...

This problem and others have been resolved in select_dialog package ([this pull-request](https://github.com/davidsdearaujo/select_dialog/pull/13)).

I will update the current package with lastest changes as soon as possible!

**Comment by davidsdearaujo** [comment]
Question solved in this commit: https://github.com/davidsdearaujo/find_dropdown/commit/68b73d194fdd4bfcc88c32ef283030f472efd747
