### ISSUE TITLE
Only lower case letters on the search box

### ISSUE THREAD

**Issue by marciorr** [davidsdearaujo/find_dropdown#20]
Is there a way to make the search box to accept only lower case letters? I'm asking because my item list consist of words starting with an uppercase letter, but when I type in the search box starting with the same uppercase letter, it doesn't find anything, but if I type all letters in lower case, it finds the respective word correctly. So, it would be good if we could force the user to type only lower case letters.
My example below:

If I have a list like this:
{Car, Flower, Dog, Cat}

and try to type in the search box:
"Car"
It doesn't return nothing.

but if I type:
"car"
It returns "Car"

The problem is that some smartphones always try to put an uppercase letter in the begining of a word, so we need to delete the letter and type a lower case instead. But for some users this is not clear and they end complaining that got no results.

Thanks in advance, and congratulations for the great work with the find_dropdown.

**Comment by davidsdearaujo** [comment]
Hi @marciorr 
In this situation, I recomend you create a new class and override the [equality operator](https://dart.dev/guides/language/effective-dart/design#equality):

```dart
class YourModel {
  final String name;

  YourModel(this.name);

  @override
  String toString() => name;

  @override
  operator ==(o) => o is YourModel && o.name.toLowerCase() == name.toLowerCase();

  @override
  int get hashCode => name.hashCode;
}
```
