### ISSUE TITLE
SetState don't update the text of the selected item 

### ISSUE THREAD

**Issue by danieramiz** [davidsdearaujo/find_dropdown#28]
After update the selected item with a setState method data inside the dropdown is correct but the text is not

![image](https://user-images.githubusercontent.com/11200295/98494946-bb722b80-2203-11eb-9d52-41352ae1cf10.png)

**Comment by davidsdearaujo** [comment]
To change the selected item, create `GlobalKey<FindDropdownState>` and access `setSelectedItem` function from state.
```
yourKey.currentState.setSelectedItem(null);
```

This implementation is exemplified in the documentation
https://pub.dev/packages/find_dropdown#change-or-clear-selected-items
