### ISSUE TITLE
doesn't support rxdart 0.25.0

### ISSUE THREAD

**Issue by nashihu** [davidsdearaujo/find_dropdown#32]
hello,,

my flutter project is using rxdart 0.25.0, can you please upgrade it? thank you..

`Because inventory depends on find_dropdown ^0.2.3 which depends on rxdart >=0.23.0 <0.25.0, rxdart >=0.23.0 <0.25.0 is required.
So, because inventory depends on rxdart ^0.25.0, version solving failed.
pub get failed (1; So, because inventory depends on rxdart ^0.25.0, version solving failed.)`

**Comment by davidsdearaujo** [comment]
This problem was solved in 1.0 version
