### ISSUE TITLE
Text overflow when is big

### ISSUE THREAD

**Issue by raphaelbarbosaqwerty** [davidsdearaujo/find_dropdown#36]
After we select a big text on the Dialog, I got an overflow on the dropdown widget because of the size of the text.

**Comment by davidsdearaujo** [comment]
Hi @raphaelbarbosaqwerty , thanks for contribute!
You can use the **drowdownBuilder** propertie to make your custom dropdown design.
This problem will be solved in next version

**Comment by davidsdearaujo** [comment]
Try the version **1.0.1-beta.3**
