### ISSUE TITLE
Null error thrown when setting multipleSelectedValues as AsyncSnapshot is null

### ISSUE THREAD

**Issue by awasum** [davidsdearaujo/find_dropdown#38]
The following TypeErrorImpl was thrown building StreamBuilder<dynamic>(dirty, state: _StreamBuilderBaseState<dynamic, AsyncSnapshot<dynamic>>#e57b9):
Unexpected null value.

The relevant error-causing widget was: 

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck
packages/find_dropdown/find_dropdown.dart 187:76                                  <fn>
packages/flutter/src/widgets/async.dart 546:81                                    build
packages/flutter/src/widgets/async.dart 124:48                                    build
...
====================================================================================================

Project Dart version: 
  sdk: ">=2.7.0 <3.0.0"

**Comment by davidsdearaujo** [comment]
Hi @awasum ,

Try using this version: [1.0.1-beta.1](https://pub.dev/packages/find_dropdown/versions/1.0.1-beta.1)
