### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [davidsdearaujo/find_dropdown#6]
Awesome package! Wouldn't it be better to use an offline example for the demo gif rather than one that queries an online API? It'll make the package appear to run smoother.
Or maybe one online, one offline 

And this is more of a searchable List dialog box instead of a Dropdown

**Comment by davidsdearaujo** [comment]
Thank you for suggestion!

**Comment by ThinkDigitalSoftware** [comment]
Anytime! Thank you!
